# Generated by Django 5.2.2 on 2025-06-18 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 2, 33, 51, 536514, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
