# Generated by Django 5.2.2 on 2025-06-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
